### ISSUE TITLE
After find, window focus still remains in tree window.

### ISSUE THREAD

**Issue by digiajay** [JKISoftware/JKI-State-Machine-Editor#32]
After searching for a state in state-machine, once the search result pops up in the new small window, change the focus to new small window immediately.  So that, I can look at the results immediately using Ctrl+G.  My usual workflow in LabVIEW find goes like this

1. Ctrl+F on tree window to get the search results.
1. Ctrl+G to start looking at the results one by one.

Else every-time after I do Ctrl+F, I need to go and focus the search result window and press the Ctrl+G.

**Comment by jimkring** [comment]
@digiajay I've tried to fix this through a variety of means, but LabVIEW is acting strange in this regard and I can't seem to find a way to give the Find Callers window the key focus it requires in order to make this work. I've also noticed that it intermittently works. I agree that your use case is valid -- I want this to work, too.

**Comment by jimkring** [comment]
I think I was able to fix this (although mights still be intermittent). The solution seems to be to not set VI as Floating in the VI Properties, but instead to set it to Floating dynamically when the VI opens its FP.

**Comment by jimkring** [comment]
Released https://github.com/JKISoftware/JKI-State-Machine-Editor/releases/tag/2013.1.2.134
