### ISSUE TITLE
SM Explorer main window disappears occasionally

### ISSUE THREAD

**Issue by arejaw** [JKISoftware/JKI-State-Machine-Editor#79]
Hello!

I don't know what causes it, but I fairly frequently do 'something' whereby I 'lose' the main SM Explorer window.  When this happens, the JKI SM Explorer option is not available to relaunch b menu or the CTRL-J hotkey. 

Closing the BD and then CTRL-E brings the BD back again, but not with the SM Explorer. I need to close out of the VI, and sometimes LV.  

Is this known or something I should be tracking down on my system (background/tray programs, for example)? I waited until I upgraded to 2018 before reporting, hoping it might go away.

Thanks.  The SM and SM Editor are awesome, I appreciate your continued efforts supporting both, and providing them to the community (among many other utilities you provide).  

Randy

Windows 10, LV2018 Pro
JKI State Machine Editor v2013.6.3.241 by JKI
Released On: Tue, 19 Jun 2018 22:20:34 -0700

**Comment by jimkring** [comment]
@arejaw this issue was (hopefully) fixed in release 2018.0.2.37. You can open VIPM and it should alert you to the new version (or you can find it in the package list). Please let us know if that helps.

**Comment by arejaw** [comment]
I have not had this occur with the new versions (I'm now using 2018.0.2.**38**), where I've had to exit Labview to recover so far - thanks!

There is some odd behavior with the SM Editor windows visibility, though.  Not a big deal, but FYI:

On dual monitors, one with the FP open and the other with the BD open:
- minimizing the BD works as expected...both the BD and SMEditor minimize.  And activating the BD again returns both in the previous locations.  
- however, first minimizing the FP and then the BD leaves the SM editor window **visible on the Desktop**.  Then maximizing the BD works fine - SMEditor and BD return to their previous locations.  If one next activates the FP window, the FP returns properly, but the SMEditor disappears.  Simply clicking on the BD brings it back though, so not really a big issue...i.e., it's not crashed.

Thanks for all the huge improvements in this new fall release - really like it.

**Comment by jimkring** [comment]
Fixed in [JKI State Machine Release 2018.0.4.39](https://github.com/JKISoftware/JKI-State-Machine/releases/tag/2018.0.4.39). Available for download and install with VIPM.

I was able to work around this issue. The problem seems to happen when the FP is already minimized, then the BD gets minimized and there are no other VIs' FP or BD open, so there's no VI Activation event that gets triggered when the target BD is minimized (there's no other VI that's active). I was able to work around this by adding a test in the Timeout frame to see if the target BD is minimized, and then will set the JKI SM Explorer window to Hidden.

Please excuse the sloppy code:
![image](https://user-images.githubusercontent.com/381432/49605032-51c8b300-f944-11e8-98fd-36c1b888750c.png)

**Comment by arejaw** [comment]
Awesome, thanks again Jim (also for fixing the Find Callers issue this morning with x.39).
It's working great, including both dual and single screen, too.  I work a lot on a remote machine with only one monitor so have the limited screen space; windows mgmt turns out to be esp important (esp for these old eyes).

**Comment by jimkring** [comment]
@arejaw you're welcome! I was able to reproduce/fix/test the issue on only a single screen, so I'm glad it's working on dual screens, too!
